### ISSUE TITLE
[Question] How do/did you add the quotes?

### ISSUE THREAD

**Issue by JunedKhan101** [Animechan-API/animechan#101]
Hi, I want to create my own api in a completely different domain and I was going through some api example project on github and stumble on this one.

My question is how do you add the quotes? I know you are querying some sort of database to get the quotes but the question remains: How do you add/maintain all these quotes? because you know there could be thousands or millions of anime quotes and of course we don't need to add all of them into our database just the most prominent quotes will do the job.

for example: I didn't find the quotes for the character Yhwach from Bleach.

In my use case, let's say for simplicilty that I want an api that returns nutrition information of all foods so I need to figure out how do I get the data? Manually adding the foods would be a pain and tedious and I don't presume that you have manually added the quotes?

Please advice.
Thanks.

**Comment by R1nge** [comment]
Just a contributor here, so I may be wrong on some parts.

The api doesn't allow for adding new quotes, partly because it's hard to monitor to the point, when it's easier to add quotes by yourself, than allow people to add them.

The second reason, it would cost much higher, because people would flood it with requests.
From my experience, if something can go wrong because of the user, it almost certainly will, so don't allow user access, that isn't required.

The third reason, people are dumb, so they will make mistakes, while adding a quote and the maintainer would have to fix it.
You may argue, than just give people access to edit quotes, but that's simply dangerous to allow.

The forth reason, api isn't mainstream, I doubt if it's even used by a hundred apps. And the traffic isn't that great, because it's a niche weabo thing.

I don't think that it's tedious to add quotes on request, it's the only option that seems reasonable to me.

So, if you want to create your own api, you'd have to migrate the db from this api.
And to do this, you'd have to either request it from a maintainer or copy it yourself, but it would be a slow process, since it allows only 60 requests per hour per IP.
Or, you can use this api inside your api, but you'd be dependent on it and have all the limitations of it.

**Comment by Kadantte** [comment]
It would be great if @rocktimsaikia added a method to how he adds these quotes to his database so people who want to make a fork of this project and host their own can add quotes to their database!
