### ISSUE TITLE
Fetching from the API returns an internal server error

### ISSUE THREAD

**Issue by YousufTheSWE** [Animechan-API/animechan#102]
Shows:

{
	error: 'Internal Server Error'
}

**Comment by Meko007** [comment]
Same here

**Comment by rocktimsaikia** [comment]
This is because PlannetScale stopped their Free tier service recently
https://planetscale.com/docs/concepts/hobby-plan-deprecation-faq#what-is-happening-to-the-hobby-tier-

I upgraded to Scaler Pro plan for now. It should work fine now.
![Screenshot from 2024-04-09 14-11-47](https://github.com/rocktimsaikia/animechan/assets/33410545/2ae693b2-e9a6-42fe-8f3c-231aeb3cfc0e)

**Comment by melosh101** [comment]
aw it sucks that they stopped with the free tier, we just recently migrated to them due to the flexibility with the free tier
